// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATSKq_WW_6hgH44C95lNj_2VnXrnPRwOA',
    appId: '1:932132120928:web:e69ad15e1d094a26c91605',
    messagingSenderId: '932132120928',
    projectId: 'communi-52801',
    authDomain: 'communi-52801.firebaseapp.com',
    storageBucket: 'communi-52801.appspot.com',
    measurementId: 'G-FYJS3TETCD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-aJotx7w0PkzGVSPvMbP71hgDKLjHmB8',
    appId: '1:932132120928:android:bdc7f2824af6c2c1c91605',
    messagingSenderId: '932132120928',
    projectId: 'communi-52801',
    storageBucket: 'communi-52801.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAODNZKZmgIvBfYILj0DToLWC2cdxEfmfA',
    appId: '1:932132120928:ios:b40131f0ce264bbdc91605',
    messagingSenderId: '932132120928',
    projectId: 'communi-52801',
    storageBucket: 'communi-52801.appspot.com',
    iosBundleId: 'com.example.chattyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAODNZKZmgIvBfYILj0DToLWC2cdxEfmfA',
    appId: '1:932132120928:ios:b40131f0ce264bbdc91605',
    messagingSenderId: '932132120928',
    projectId: 'communi-52801',
    storageBucket: 'communi-52801.appspot.com',
    iosBundleId: 'com.example.chattyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATSKq_WW_6hgH44C95lNj_2VnXrnPRwOA',
    appId: '1:932132120928:web:6b1dd035cd1b6251c91605',
    messagingSenderId: '932132120928',
    projectId: 'communi-52801',
    authDomain: 'communi-52801.firebaseapp.com',
    storageBucket: 'communi-52801.appspot.com',
    measurementId: 'G-HG8VDKFEVQ',
  );
}
